app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb

Please take a look at this and accept or request changes

Created simple footer with social media links

---

app/models/booking.rb
app/models/plane.rb
app/models/user.rb
db/migrate/20220823110345_create_bookings.rb
db/schema.rb
test/models/booking_test.rb

just created the the booking model

created the booking model

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/planes_controller.rb
app/policies/application_policy.rb
app/policies/plane_policy.rb
app/views/planes/show.html.erb
test/policies/plane_policy_test.rb

HI, I did authorization to manage planes. 
- Now all users can see offers and create an offer.
- Only the creator of an offer can edit it or remove it.
Can you check before merging @1zach ?

authorization done

---

app/views/planes/booking.html.erb
app/views/planes/new.html.erb

Hey guys, here is the file for the booking "view", how awesome is it?

Steph created the booking views

---

app/controllers/bookings_controller.rb
config/routes.rb
test/controllers/bookings_controller_test.rb

hey guys, I just made the core structure of the bookings. routes and controller core, now I want to test it

finnished the base of the controller and the routes for booking tables

---

app/models/plane.rb
db/seeds.rb

hey coco i had created an seeds of 15 planes  with 5 users. i hope you like it if not it not my problem.
thank you 
with  respect 
tenzin

created seed file with 5 users and 15 planes

---

app/assets/stylesheets/components/_btn-black.scss
app/assets/stylesheets/components/_home_card.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_search_box.scss
app/assets/stylesheets/components/_show_card.scss
app/assets/stylesheets/pages/_home.scss
app/views/layouts/application.html.erb
app/views/pages/_banner.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_search-box.html.erb

Cleaned up a few broken links, added search bar

Cleaned up frontpage

---

app/controllers/bookings_controller.rb
app/models/plane.rb
app/policies/booking_policy.rb
app/views/bookings/new.html.erb
test/policies/booking_policy_test.rb

booking authorisations done inshallah

---

app/views/shared/_navbar.html.erb

Created named link in navbar

---

app/views/planes/show.html.erb
app/views/shared/_navbar.html.erb

delete button present but doesnt work and more info on show page about planes @1zach

Booking button

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss

I made a few minor changes on the landing page, please review it :)

Steph front navbar

---

.gitignore
app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_search_box.scss
app/views/pages/_banner.html.erb
app/views/pages/home.html.erb

fixbanner is done

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_home_card.scss
app/assets/stylesheets/components/_show_card.scss
app/views/planes/index.html.erb

I changed the design for the "fleet" page, here is what it looks like, please review my code:

Steph planes page

---

app/assets/stylesheets/components/_form_show_page.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_info_show_plane.scss
app/views/planes/show.html.erb

Ambbuck plane show page

---

app/views/layouts/application.html.erb
app/views/pages/_banner.html.erb
app/views/pages/home.html.erb

Fixed banner margin

---

app/assets/stylesheets/components/_home_card.scss
app/views/planes/_home-planes.html.erb

Home cards have link on photo, but not whole card

---

.gitignore
app/controllers/bookings_controller.rb
app/views/bookings/new.html.erb
app/views/planes/show.html.erb

date available

---

app/assets/stylesheets/components/_booking.scss
app/assets/stylesheets/components/_index.scss
app/views/bookings/new.html.erb
app/views/planes/booking.html.erb

changed minor things on the booking design

---

app/views/planes/show.html.erb

Fixed destroy link

---

app/views/shared/_navbar.html.erb
config/environments/production.rb

Fixcloudinary

---

app/views/shared/_navbar.html.erb

Fixed navbar

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/pages/_home.scss
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb

Avatar and footer fixed...I think

Fixed avatar and footer

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_search_box.scss
app/javascript/controllers/index.js
app/javascript/controllers/typed_js_controller.js
app/views/pages/_banner.html.erb
package.json
yarn.lock

Added typejs to the app and to the banner

---

app/assets/stylesheets/components/_info_show_plane.scss
app/views/planes/index.html.erb

Fixed blue button on plane index page

---

app/assets/stylesheets/components/_search_box.scss
app/views/pages/_banner.html.erb
app/views/shared/_search-box.html.erb

new design search item

---

app/controllers/bookings_controller.rb

negative price fixed

---

app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_index.scss
app/views/bookings/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/planes/edit.html.erb
app/views/planes/new.html.erb

form done inshallah

---

app/assets/stylesheets/components/_info_show_plane.scss
app/assets/stylesheets/components/_show_card.scss
app/views/planes/_show-planes.html.erb
app/views/planes/index.html.erb

The cards and buttons are now clickable.
The cards now have fontawesome icons instead of text.

clickable cards and buttons on the show-planes

---

app/views/planes/show.html.erb

trash icon for booking list

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

I put the sign up button in the navbar when you visit the website

finished the sign up button in the navbar

---

app/assets/stylesheets/components/_home_card.scss
app/views/planes/_home-planes.html.erb

card on gome page changed

---

app/assets/stylesheets/components/_btn-plane.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_info_show_plane.scss
app/views/planes/show.html.erb

card plane done

---

app/assets/stylesheets/components/_info_show_plane.scss
app/assets/stylesheets/config/_fonts.scss

fonts for website

---

app/assets/stylesheets/pages/_user.scss
app/views/pages/_banner.html.erb

Removed contact us button

---

app/assets/stylesheets/components/_colage.scss
app/assets/stylesheets/components/_info_show_plane.scss
app/assets/stylesheets/components/_show_card.scss
app/views/planes/show.html.erb

img show card fied

---

app/assets/stylesheets/components/_btn-plane.scss
app/assets/stylesheets/components/_content.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_home_card.scss
app/assets/stylesheets/components/_info_show_plane.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_show_card.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_user.scss
app/views/shared/_footer.html.erb

I changed colors for the website :

colors for our website

---

app/views/shared/_avatar.html.erb

minor change

---

app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_user.scss
app/views/planes/_show-planes.html.erb

few changes

---

app/assets/stylesheets/components/_search_box.scss
app/views/shared/_search-box.html.erb

finnished the frontend of the search bar

---

app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/config/_colors.scss

Changed the color for the form:

changed the form colors

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_planes.scss
app/views/planes/index.html.erb

Our planes updated

---

app/assets/stylesheets/components/_home_card.scss
app/assets/stylesheets/components/_show_card.scss

home card done remove shadoww border and repeting image

---

app/assets/stylesheets/components/_banner.scss

Changed height of banner for demo screen

Changed height and font size of banner

---

app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/pages/_bookings.scss

bookings page frontend

---

app/assets/stylesheets/components/_banner.scss
app/views/bookings/show.html.erb
app/views/layouts/application.html.erb

Fixed username error on booking show
